landscapeName: lf
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
   - name: Silver Membership - MPSF
     category: Silver
   - name: Associate Membership
     category: Associate
project: a0941000002wBz9AAE # The Linux Foundation
landscapeMemberCategory: LF Members
landscapefile: landscape.yml
defaultCrunchbase: https://www.crunchbase.com/organization/linux-foundation
missingcsvfile: missing.csv
