name: "Set Issue Label on successful build"
on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        if: contains(github.event.pull_request.labels.*.name, 'daily-update')
        with:
          keywords: '["Deploy preview for lf-landscape ready!"]'
          labels: '["automerge"]'
          github-token: "${{ secrets.PAT }}"
